### PR TITLE
lemme read pt2

### PR DESCRIPTION
**Pull request by lokzz**
yea

### CODE REVIEW

**Comment by username-is-required** [comment]
lgtm

**Comment by username-is-required** [comment]
think i’m gonna do the next reload in about 8 minutes to coincide with when my script would autorefresh the subreddit list anyway, and when that happenz that your change will be pushed

**Comment by username-is-required** [comment]
@lokzz this should now be live, let me know if it isn’t working

**Comment by lokzz** [comment]
yep!

**Pull request merged**
