### PR TITLE
let me read

### PR DESCRIPTION
**Pull request by lokzz**
lemme read what subs go private
(just adds a data.name to the console.log)

### CODE REVIEW

**Comment by username-is-required** [comment]
looks good, i’ll reload the server at some point with the no-alerting filter for spamming subreddits. when i do that this’ll be pushed as well

**Comment by lokzz** [comment]
thx!

**Comment by username-is-required** [comment]
actually sorry to be funny but can you recreate this but to merge with `main` instead of `digital-ocean`?  every push to the DO branch means the server automatically reloads so i like to have them in `main` first and then merge `main` to `digital-ocean`.

**Comment by lokzz** [comment]
ok

**Comment by lokzz** [comment]
#41

**Pull request closed without merging**
